version: "3"
services:
    oneclick:
        build: .
        image: gaia
        ports:
            - '8080:8080'
        environment:
            - "ONECLICK_MONGODB_URI=mongodb://mongo/oneclick"
            - "ONECLICK_EXTERNAL_URL=http://172.17.0.1:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mongo:
        build:
            context: .
            dockerfile: ./Dockerfile-db
        image: gaia-db
        volumes:
            - ~/.mongodb/:/var/lib/mongodb
